In [1]:
# Import libraries

import pandas as pd
import numpy as np
import os

In [2]:
path = r'/Users/swapnilgadage/Documents/DataAnalytics/Achivment 4/06.11.2024_Instacart Basket Analysis'

In [5]:
# Importing Dataset

In [7]:
ords_prods_merge=pd.read_pickle(os.path.join(path, 'Data', 'Prepared Data', 'orders_products_merged_derived.pkl'))

In [9]:
# Create a subset of 1 million rows
df = ords_prods_merge[:1000000]

In [11]:
# Check shape of new subset
df.shape

(1000000, 19)

In [13]:
df.head(10)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,match,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,prior,1,2,8,NaN,196,1,0,both,Soda,77,7,9.0,both,Regularly busy,Regularly busy,Average orders
1,2539329,1,prior,1,2,8,NaN,14084,2,0,both,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Regularly busy,Regularly busy,Average orders
2,2539329,1,prior,1,2,8,NaN,12427,3,0,both,Original Beef Jerky,23,19,4.4,both,Regularly busy,Regularly busy,Average orders
3,2539329,1,prior,1,2,8,NaN,26088,4,0,both,Aged White Cheddar Popcorn,23,19,4.7,both,Regularly busy,Regularly busy,Average orders
4,2539329,1,prior,1,2,8,NaN,26405,5,0,both,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Regularly busy,Regularly busy,Average orders
5,2398795,1,prior,2,3,7,15.0,196,1,1,both,Soda,77,7,9.0,both,Regularly busy,Slowest days,Average orders
6,2398795,1,prior,2,3,7,15.0,10258,2,0,both,Pistachios,117,19,3.0,both,Regularly busy,Slowest days,Average orders
7,2398795,1,prior,2,3,7,15.0,12427,3,1,both,Original Beef Jerky,23,19,4.4,both,Regularly busy,Slowest days,Average orders
8,2398795,1,prior,2,3,7,15.0,13176,4,0,both,Bag of Organic Bananas,24,4,10.3,both,Regularly busy,Slowest days,Average orders
9,2398795,1,prior,2,3,7,15.0,26088,5,1,both,Aged White Cheddar Popcorn,23,19,4.7,both,Regularly busy,Slowest days,Average orders

In [19]:
df.groupby('product_name')
#Grouping Data with pandas

In [17]:
# Aggregating Data with agg()  
# Single aggregation
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                14.800024
2                17.091743
3                17.913544
4                17.893092
5                15.214270
6                15.382135
7                17.694027
8                16.458105
9                15.957363
10               20.091818
11               16.482026
12               15.615061
13               16.484023
14               17.524632
15               15.691875
16               18.014071
17               16.150593
18               19.602850
19               17.631340
20               17.138607
21               21.956893

In [21]:
# same output but without aggregation function
df.groupby('department_id')['order_number'].mean()

department_id
1     14.800024
2     17.091743
3     17.913544
4     17.893092
5     15.214270
6     15.382135
7     17.694027
8     16.458105
9     15.957363
10    20.091818
11    16.482026
12    15.615061
13    16.484023
14    17.524632
15    15.691875
16    18.014071
17    16.150593
18    19.602850
19    17.631340
20    17.138607
21    21.956893
Name: order_number, dtype: float64

In [23]:
# Performing Multiple Aggregations
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                14.800024   1  99
2                17.091743   1  98
3                17.913544   1  99
4                17.893092   1  99
5                15.214270   1  99
6                15.382135   1  99
7                17.694027   1  99
8                16.458105   1  91
9                15.957363   1  99
10               20.091818   1  99
11               16.482026   1  99
12               15.615061   1  99
13               16.484023   1  99
14               17.524632   1  99
15               15.691875   1  99
16               18.014071   1  99
17               16.150593   1  99
18               19.602850   1  99
19               17.631340   1  99
20               17.138607   1  99
21               21.956893   1  97

In [27]:
# Aggregating Data with transform()
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform('max')

In [29]:
ords_prods_merge.head(15)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,match,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8,NaN,196,1,0,both,Soda,77,7,9.0,both,Regularly busy,Regularly busy,Average orders,10
1,2539329,1,prior,1,2,8,NaN,14084,2,0,both,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Regularly busy,Regularly busy,Average orders,10
2,2539329,1,prior,1,2,8,NaN,12427,3,0,both,Original Beef Jerky,23,19,4.4,both,Regularly busy,Regularly busy,Average orders,10
3,2539329,1,prior,1,2,8,NaN,26088,4,0,both,Aged White Cheddar Popcorn,23,19,4.7,both,Regularly busy,Regularly busy,Average orders,10
4,2539329,1,prior,1,2,8,NaN,26405,5,0,both,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Regularly busy,Regularly busy,Average orders,10
5,2398795,1,prior,2,3,7,15.0,196,1,1,both,Soda,77,7,9.0,both,Regularly busy,Slowest days,Average orders,10
6,2398795,1,prior,2,3,7,15.0,10258,2,0,both,Pistachios,117,19,3.0,both,Regularly busy,Slowest days,Average orders,10
7,2398795,1,prior,2,3,7,15.0,12427,3,1,both,Original Beef Jerky,23,19,4.4,both,Regularly busy,Slowest days,Average orders,10
8,2398795,1,prior,2,3,7,15.0,13176,4,0,both,Bag of Organic Bananas,24,4,10.3,both,Regularly busy,Slowest days,Average orders,10
9,2398795,1,prior,2,3,7,15.0,26088,5,1,both,Aged White Cheddar Popcorn,23,19,4.7,both,Regularly busy,Slowest days,Average orders,10
10,2398795,1,prior,2,3,7,15.0,13032,6,0,both,Cinnamon Toast Crunch,121,14,4.0,both,Regularly busy,Slowest days,Average orders,10
11,473747,1,prior,3,3,12,21.0,196,1,1,both,Soda,77,7,9.0,both,Regularly busy,Slowest days,Most orders,10
12,473747,1,prior,3,3,12,21.0,12427,2,1,both,Original Beef Jerky,23,19,4.4,both,Regularly busy,Slowest days,Most orders,10
13,473747,1,prior,3,3,12,21.0,10258,3,1,both,Pistachios,117,19,3.0,both,Regularly busy,Slowest days,Most orders,10
14,473747,1,prior,3,3,12,21.0,25133,4,0,both,Organic String Cheese,21,16,8.6,both,Regularly busy,Slowest days,Most orders,10

In [31]:
ords_prods_merge.head(100)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,match,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8,NaN,196,1,0,both,Soda,77,7,9.0,both,Regularly busy,Regularly busy,Average orders,10
1,2539329,1,prior,1,2,8,NaN,14084,2,0,both,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Regularly busy,Regularly busy,Average orders,10
2,2539329,1,prior,1,2,8,NaN,12427,3,0,both,Original Beef Jerky,23,19,4.4,both,Regularly busy,Regularly busy,Average orders,10
3,2539329,1,prior,1,2,8,NaN,26088,4,0,both,Aged White Cheddar Popcorn,23,19,4.7,both,Regularly busy,Regularly busy,Average orders,10
4,2539329,1,prior,1,2,8,NaN,26405,5,0,both,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Regularly busy,Regularly busy,Average orders,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,738281,2,prior,4,2,10,8.0,21150,13,0,both,Fire Grilled Steak Bowl,38,1,5.9,both,Regularly busy,Regularly busy,Most orders,14
96,1673511,2,prior,5,3,11,8.0,47144,1,0,both,Unsweetened Original Almond Breeze Almond Milk,91,16,14.0,both,Regularly busy,Slowest days,Most orders,14
97,1673511,2,prior,5,3,11,8.0,5322,2,0,both,Gluten Free Dark Chocolate Chunk Chewy with a ...,3,19,2.9,both,Regularly busy,Slowest days,Most orders,14
98,1673511,2,prior,5,3,11,8.0,17224,3,0,both,Oats & Honey Gluten Free Granola,3,19,1.6,both,Regularly busy,Slowest days,Most orders,14
99,1673511,2,prior,5,3,11,8.0,38656,4,0,both,Gluten Free Peanut Butter Dark Chocolate Chewy...,3,19,3.4,both,Regularly busy,Slowest days,Most orders,14

In [33]:
pd.options.display.max_rows = None

In [35]:
ords_prods_merge.head(100)

,order_id,user_id,eval_set,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,match,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,prior,1,2,8,NaN,196,1,0,both,Soda,77,7,9.0,both,Regularly busy,Regularly busy,Average orders,10
1,2539329,1,prior,1,2,8,NaN,14084,2,0,both,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,both,Regularly busy,Regularly busy,Average orders,10
2,2539329,1,prior,1,2,8,NaN,12427,3,0,both,Original Beef Jerky,23,19,4.4,both,Regularly busy,Regularly busy,Average orders,10
3,2539329,1,prior,1,2,8,NaN,26088,4,0,both,Aged White Cheddar Popcorn,23,19,4.7,both,Regularly busy,Regularly busy,Average orders,10
4,2539329,1,prior,1,2,8,NaN,26405,5,0,both,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Regularly busy,Regularly busy,Average orders,10
5,2398795,1,prior,2,3,7,15.0,196,1,1,both,Soda,77,7,9.0,both,Regularly busy,Slowest days,Average orders,10
6,2398795,1,prior,2,3,7,15.0,10258,2,0,both,Pistachios,117,19,3.0,both,Regularly busy,Slowest days,Average orders,10
7,2398795,1,prior,2,3,7,15.0,12427,3,1,both,Original Beef Jerky,23,19,4.4,both,Regularly busy,Slowest days,Average orders,10
8,2398795,1,prior,2,3,7,15.0,13176,4,0,both,Bag of Organic Bananas,24,4,10.3,both,Regularly busy,Slowest days,Average orders,10
9,2398795,1,prior,2,3,7,15.0,26088,5,1,both,Aged White Cheddar Popcorn,23,19,4.7,both,Regularly busy,Slowest days,Average orders,10
10,2398795,1,prior,2,3,7,15.0,13032,6,0,both,Cinnamon Toast Crunch,121,14,4.0,both,Regularly busy,Slowest days,Average orders,10
11,473747,1,prior,3,3,12,21.0,196,1,1,both,Soda,77,7,9.0,both,Regularly busy,Slowest days,Most orders,10
12,473747,1,prior,3,3,12,21.0,12427,2,1,both,Original Beef Jerky,23,19,4.4,both,Regularly busy,Slowest days,Most orders,10
13,473747,1,prior,3,3,12,21.0,10258,3,1,both,Pistachios,117,19,3.0,both,Regularly busy,Slowest days,Most orders,10
14,473747,1,prior,3,3,12,21.0,25133,4,0,both,Organic String Cheese,21,16,8.6,both,Regularly busy,Slowest days,Most orders,10
15,473747,1,prior,3,3,12,21.0,30450,5,0,both,Creamy Almond Butter,88,13,3.2,both,Regularly busy,Slowest days,Most orders,10
16,2254736,1,prior,4,4,7,29.0,196,1,1,both,Soda,77,7,9.0,both,Least busy,Slowest days,Average orders,10
17,2254736,1,prior,4,4,7,29.0,12427,2,1,both,Original Beef Jerky,23,19,4.4,both,Least busy,Slowest days,Average orders,10
18,2254736,1,prior,4,4,7,29.0,10258,3,1,both,Pistachios,117,19,3.0,both,Least busy,Slowest days,Average orders,10
19,2254736,1,prior,4,4,7,29.0,25133,4,1,both,Organic String Cheese,21,16,8.6,both,Least busy,Slowest days,Average orders,10
20,2254736,1,prior,4,4,7,29.0,26405,5,1,both,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,both,Least busy,Slowest days,Average orders,10
21,431534,1,prior,5,4,15,28.0,196,1,1,both,Soda,77,7,9.0,both,Least busy,Slowest days,Most orders,10
22,431534,1,prior,5,4,15,28.0,12427,2,1,both,Original Beef Jerky,23,19,4.4,both,Least busy,Slowest days,Most orders,10
23,431534,1,prior,5,4,15,28.0,10258,3,1,both,Pistachios,117,19,3.0,both,Least busy,Slowest days,Most orders,10
24,431534,1,prior,5,4,15,28.0,25133,4,1,both,Organic String Cheese,21,16,8.6,both,Least busy,Slowest days,Most orders,10
25,431534,1,prior,5,4,15,28.0,10326,5,0,both,Organic Fuji Apples,24,4,2.7,both,Least busy,Slowest days,Most orders,10
26,431534,1,prior,5,4,15,28.0,17122,6,0,both,Honeycrisp Apples,24,4,14.0,both,Least busy,Slowest days,Most orders,10
27,431534,1,prior,5,4,15,28.0,41787,7,0,both,Bartlett Pears,24,4,5.0,both,Least busy,Slowest days,Most orders,10
28,431534,1,prior,5,4,15,28.0,13176,8,1,both,Bag of Organic Bananas,24,4,10.3,both,Least busy,Slowest days,Most orders,10
29,3367565,1,prior,6,2,7,19.0,196,1,1,both,Soda,77,7,9.0,both,Regularly busy,Regularly busy,Average orders,10
30,3367565,1,prior,6,2,7,19.0,12427,2,1,both,Original Beef Jerky,23,19,4.4,both,Regularly busy,Regularly busy,Average orders,10
31,3367565,1,prior,6,2,7,19.0,10258,3,1,both,Pistachios,117,19,3.0,both,Regularly busy,Regularly busy,Average orders,10
32,3367565,1,prior,6,2,7,19.0,25133,4,1,both,Organic String Cheese,21,16,8.6,both,Regularly busy,Regularly busy,Average orders,10
33,550135,1,prior,7,1,9,20.0,196,1,1,both,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,10
34,550135,1,prior,7,1,9,20.0,10258,2,1,both,Pistachios,117,19,3.0,both,Regularly busy,Busiest days,Most orders,10
35,550135,1,prior,7,1,9,20.0,12427,3,1,both,Original Beef Jerky,23,19,4.4,both,Regularly busy,Busiest days,Most orders,10
36,550135,1,prior,7,1,9,20.0,25133,4,1,both,Organic String Cheese,21,16,8.6,both,Regularly busy,Busiest days,Most orders,10
37,550135,1,prior,7,1,9,20.0,13032,5,1,both,Cinnamon Toast Crunch,121,14,4.0,both,Regularly busy,Busiest days,Most orders,10
38,3108588,1,prior,8,1,14,14.0,12427,1,1,both,Original Beef Jerky,23,19,4.4,both,Regularly busy,Busiest days,Most orders,10
39,3108588,1,prior,8,1,14,14.0,196,2,1,both,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,10
40,3108588,1,prior,8,1,14,14.0,10258,3,1,both,Pistachios,117,19,3.0,both,Regularly busy,Busiest days,Most orders,10
41,3108588,1,prior,8,1,14,14.0,25133,4,1,both,Organic String Cheese,21,16,8.6,both,Regularly busy,Busiest days,Most orders,10
42,3108588,1,prior,8,1,14,14.0,46149,5,0,both,Zero Calorie Cola,77,7,13.4,both,Regularly busy,Busiest days,Most orders,10
43,3108588,1,prior,8,1,14,14.0,49235,6,0,both,Organic Half & Half,53,16,1.8,both,Regularly busy,Busiest days,Most orders,10
44,2295261,1,prior,9,1,16,0.0,49235,1,1,both,Organic Half & Half,53,16,1.8,both,Regularly busy,Busiest days,Most orders,10
45,2295261,1,prior,9,1,16,0.0,46149,2,1,both,Zero Calorie Cola,77,7,13.4,both,Regularly busy,Busiest days,Most orders,10
46,2295261,1,prior,9,1,16,0.0,25133,3,1,both,Organic String Cheese,21,16,8.6,both,Regularly busy,Busiest days,Most orders,10
47,2295261,1,prior,9,1,16,0.0,196,4,1,both,Soda,77,7,9.0,both,Regularly busy,Busiest days,Most orders,10
48,2295261,1,prior,9,1,16,0.0,10258,5,1,both,Pistachios,117,19,3.0,both,Regularly busy,Busiest days,Most orders,10
49,2295261,1,prior,9,1,16,0.0,12427,6,1,both,Original Beef Jerky,23,19,4.4,both,Regularly busy,Busiest days,Most orders,10
50,2550362,1,prior,10,4,8,30.0,196,1,1,both,Soda,77,7,9.0,both,Least busy,Slowest days,Average orders,10
51,2550362,1,prior,10,4,8,30.0,46149,2,1,both,Zero Calorie Cola,77,7,13.4,both,Least busy,Slowest days,Average orders,10
52,2550362,1,prior,10,4,8,30.0,39657,3,0,both,Milk Chocolate Almonds,45,19,6.8,both,Least busy,Slowest days,Average orders,10
53,2550362,1,prior,10,4,8,30.0,38928,4,0,both,0% Greek Strained Yogurt,120,16,12.6,both,Least busy,Slowest days,Average orders,10
54,2550362,1,prior,10,4,8,30.0,25133,5,1,both,Organic String Cheese,21,16,8.6,both,Least busy,Slowest days,Average orders,10
55,2550362,1,prior,10,4,8,30.0,10258,6,1,both,Pistachios,117,19,3.0,both,Least busy,Slowest days,Average orders,10
56,2550362,1,prior,10,4,8,30.0,35951,7,0,both,Organic Unsweetened Almond Milk,91,16,1.3,both,Least busy,Slowest days,Average orders,10
57,2550362,1,prior,10,4,8,30.0,13032,8,1,both,Cinnamon Toast Crunch,121,14,4.0,both,Least busy,Slowest days,Average orders,10
58,2550362,1,prior,10,4,8,30.0,12427,9,1,both,Original Beef Jerky,23,19,4.4,both,Least busy,Slowest days,Average orders,10
59,2168274,2,prior,1,2,11,NaN,32792,1,0,both,Chipotle Beef & Pork Realstick,23,19,5.2,both,Regularly busy,Regularly busy,Most orders,14
60,2168274,2,prior,1,2,11,NaN,47766,2,0,both,Organic Avocado,24,4,6.3,both,Regularly busy,Regularly busy,Most orders,14
61,2168274,2,prior,1,2,11,NaN,20574,3,0,both,Roasted Turkey,96,20,2.3,both,Regularly busy,Regularly busy,Most orders,14
62,2168274,2,prior,1,2,11,NaN,12000,4,0,both,Baked Organic Sea Salt Crunchy Pea Snack,72,13,10.9,both,Regularly busy,Regularly busy,Most orders,14
63,2168274,2,prior,1,2,11,NaN,48110,5,0,both,Thin Stackers Brown Rice Lightly Salted,78,19,2.7,both,Regularly busy,Regularly busy,Most orders,14
64,2168274,2,prior,1,2,11,NaN,22474,6,0,both,Cheddar Bunnies Snack Crackers,78,19,4.1,both,Regularly busy,Regularly busy,Most orders,14
65,2168274,2,prior,1,2,11,NaN,16589,7,0,both,Plantain Chips,107,19,5.0,both,Regularly busy,Regularly busy,Most orders,14
66,2168274,2,prior,1,2,11,NaN,35917,8,0,both,Organic Just Concord Grape Juice,98,7,9.4,both,Regularly busy,Regularly busy,Most orders,14
67,2168274,2,prior,1,2,11,NaN,27344,9,0,both,Uncured Genoa Salami,96,20,14.8,both,Regularly busy,Regularly busy,Most orders,14
68,2168274,2,prior,1,2,11,NaN,30489,10,0,both,Original Hummus,67,20,7.5,both,Regularly busy,Regularly busy,Most orders,14
69,2168274,2,prior,1,2,11,NaN,27966,11,0,both,Organic Raspberries,123,4,4.4,both,Regularly busy,Regularly busy,Most orders,14
70,2168274,2,prior,1,2,11,NaN,13176,12,0,both,Bag of Organic Bananas,24,4,10.3,both,Regularly busy,Regularly busy,Most orders,14
71,2168274,2,prior,1,2,11,NaN,45066,13,0,both,Honeycrisp Apple,24,4,2.5,both,Regularly busy,Regularly busy,Most orders,14
72,1501582,2,prior,2,5,10,10.0,16797,1,0,both,Strawberries,24,4,1.3,both,Regularly busy,Regularly busy,Most orders,14
73,1501582,2,prior,2,5,10,10.0,47526,2,0,both,Goat Cheese Log,21,16,2.0,both,Regularly busy,Regularly busy,Most orders,14
74,1501582,2,prior,2,5,10,10.0,8479,3,0,both,Original Black Box Tablewater Cracker,78,19,3.5,both,Regularly busy,Regularly busy,Most orders,14
75,1501582,2,prior,2,5,10,10.0,47766,4,1,both,Organic Avocado,24,4,6.3,both,Regularly busy,Regularly busy,Most orders,14
76,1501582,2,prior,2,5,10,10.0,19051,5,0,both,"Pita Chips, Simply Naked, Party Size",107,19,3.9,both,Regularly busy,Regularly busy,Most orders,14
77,1501582,2,prior,2,5,10,10.0,8138,6,0,both,Traditional Hummus,67,20,2.0,both,Regularly busy,Regularly busy,Most orders,14
78,1901567,2,prior,3,1,10,3.0,47766,1,1,both,Organic Avocado,24,4,6.3,both,Regularly busy,Busiest days,Most orders,14
79,1901567,2,prior,3,1,10,3.0,32792,2,1,both,Chipotle Beef & Pork Realstick,23,19,5.2,both,Regularly busy,Busiest days,Most orders,14
80,1901567,2,prior,3,1,10,3.0,20574,3,1,both,Roasted Turkey,96,20,2.3,both,Regularly busy,Busiest days,Most orders,14
81,1901567,2,prior,3,1,10,3.0,7781,4,0,both,Organic Sticks Low Moisture Part Skim Mozzarel...,21,16,6.6,both,Regularly busy,Busiest days,Most orders,14
82,1901567,2,prior,3,1,10,3.0,28874,5,0,both,Carrot Ginger Soup,1,20,6.2,both,Regularly busy,Busiest days,Most orders,14
83,738281,2,prior,4,2,10,8.0,49451,1,0,both,Artichoke Spinach Dip,67,20,7.1,both,Regularly busy,Regularly busy,Most orders,14
84,738281,2,prior,4,2,10,8.0,32792,2,1,both,Chipotle Beef & Pork Realstick,23,19,5.2,both,Regularly busy,Regularly busy,Most orders,14
85,738281,2,prior,4,2,10,8.0,32139,3,0,both,Hommus Classic Original,67,20,7.5,both,Regularly busy,Regularly busy,Most orders,14
86,738281,2,prior,4,2,10,8.0,34688,4,0,both,Good Belly Probiotics Juice Drink Blueberry Ac...,31,7,5.8,both,Regularly busy,Regularly busy,Most orders,14
87,738281,2,prior,4,2,10,8.0,36735,5,0,both,Organic Roasted Sliced Chicken Breast,96,20,8.9,both,Regularly busy,Regularly busy,Most orders,14
88,738281,2,prior,4,2,10,8.0,37646,6,0,both,Organic Gala Apples,24,4,9.1,both,Regularly busy,Regularly busy,Most orders,14
89,738281,2,prior,4,2,10,8.0,22829,7,0,both,Multigrain Flax Seeded Flatbread Crackers,78,19,5.5,both,Regularly busy,Regularly busy,Most orders,14
90,738281,2,prior,4,2,10,8.0,24852,8,0,both,Banana,24,4,12.3,both,Regularly busy,Regularly busy,Most orders,14
91,738281,2,prior,4,2,10,8.0,47209,9,0,both,Organic Hass Avocado,24,4,4.0,both,Regularly busy,Regularly busy,Most orders,14
92,738281,2,prior,4,2,10,8.0,33276,10,0,both,Kalamata Olive Spread,67,20,10.8,both,Regularly busy,Regularly busy,Most orders,14
93,738281,2,prior,4,2,10,8.0,45613,11,0,both,Pad Thai,38,1,12.6,both,Regularly busy,Regularly busy,Most orders,14
94,738281,2,prior,4,2,10,8.0,9681,12,0,both,Chicken Tikka Masala with Cumin Infused Basmat...,38,1,2.0,both,Regularly busy,Regularly busy,Most orders,14
95,738281,2,prior,4,2,10,8.0,21150,13,0,both,Fire Grilled Steak Bowl,38,1,5.9,both,Regularly busy,Regularly busy,Most orders,14
96,1673511,2,prior,5,3,11,8.0,47144,1,0,both,Unsweetened Original Almond Breeze Almond Milk,91,16,14.0,both,Regularly busy,Slowest days,Most orders,14
97,1673511,2,prior,5,3,11,8.0,5322,2,0,both,Gluten Free Dark Chocolate Chunk Chewy with a ...,3,19,2.9,both,Regularly busy,Slowest days,Most orders,14
98,1673511,2,prior,5,3,11,8.0,17224,3,0,both,Oats & Honey Gluten Free Granola,3,19,1.6,both,Regularly busy,Slowest days,Most orders,14
99,1673511,2,prior,5,3,11,8.0,38656,4,0,both,Gluten Free Peanut Butter Dark Chocolate Chewy...,3,19,3.4,both,Regularly busy,Slowest days,Most orders,14

In [37]:
# from abouve function Now, all 100 rows we called for can be viewed.

In [39]:
# Deriving Columns with loc()

In [41]:
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [43]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [45]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [47]:
#  Check value counts for new column
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64

In [49]:
# Most customers fall into the 'Regular customer' category

In [53]:
# As always, check that everything was interpreted correctly and that the right flags were assigned 
ords_prods_merge[['user_id', 'loyalty_flag', 'order_number']].head(60)

    user_id      loyalty_flag  order_number
0         1      New customer             1
1         1      New customer             1
2         1      New customer             1
3         1      New customer             1
4         1      New customer             1
5         1      New customer             2
6         1      New customer             2
7         1      New customer             2
8         1      New customer             2
9         1      New customer             2
10        1      New customer             2
11        1      New customer             3
12        1      New customer             3
13        1      New customer             3
14        1      New customer             3
15        1      New customer             3
16        1      New customer             4
17        1      New customer             4
18        1      New customer             4
19        1      New customer             4
20        1      New customer             4
21        1      New customer             5
22        1      New customer             5
23        1      New customer             5
24        1      New customer             5
25        1      New customer             5
26        1      New customer             5
27        1      New customer             5
28        1      New customer             5
29        1      New customer             6
30        1      New customer             6
31        1      New customer             6
32        1      New customer             6
33        1      New customer             7
34        1      New customer             7
35        1      New customer             7
36        1      New customer             7
37        1      New customer             7
38        1      New customer             8
39        1      New customer             8
40        1      New customer             8
41        1      New customer             8
42        1      New customer             8
43        1      New customer             8
44        1      New customer             9
45        1      New customer             9
46        1      New customer             9
47        1      New customer             9
48        1      New customer             9
49        1      New customer             9
50        1      New customer            10
51        1      New customer            10
52        1      New customer            10
53        1      New customer            10
54        1      New customer            10
55        1      New customer            10
56        1      New customer            10
57        1      New customer            10
58        1      New customer            10
59        2  Regular customer             1

In [55]:
# Export dataframe with newly derived columns

In [57]:
ords_prods_merge.to_pickle(os.path.join(path, 'Data','Prepared Data', 'orders_products_combined_merged_new_variables_derived.pkl'))